"""empty message

Revision ID: db5fa3adf1e9
Revises: afd370852ebf
Create Date: 2020-08-09 23:49:53.074003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5fa3adf1e9'
down_revision = 'afd370852ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('length_of_article', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'length_of_article')
    # ### end Alembic commands ###
